name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache bash python3 py3-pip openjdk17-jre wget
        wget https://github.com/ontodev/robot/releases/latest/download/robot.jar -O /usr/local/bin/robot.jar
        echo '#!/bin/sh\njava -jar /usr/local/bin/robot.jar "$@"' > /usr/local/bin/robot
        chmod +x /usr/local/bin/robot

    - name: Merge ontology
      run: |
        chmod +x scripts/merge_ontology.sh
        ./scripts/merge_ontology.sh . automobile_merged.ttl

    - name: Basic RDF validation
      run: riot --validate automobile_merged.ttl

    - name: Run ROBOT validation
      id: robot_validation
      continue-on-error: true
      run: |
        mkdir -p validation-reports
        # Generate report in TSV format (more reliable)
        robot report --input automobile_merged.ttl --format tsv --output validation-reports/report.tsv
        
        # Run SPARQL validation if queries exist
        if [ -d sparql/validation_queries ] && [ -n "$(ls sparql/validation_queries/*.rq 2>/dev/null)" ]; then
          robot verify --input automobile_merged.ttl \
            --queries sparql/validation_queries/*.rq \
            --output-dir validation-reports/verify/
        fi

    - name: Process validation results
      run: |
        echo "Validation artifacts:"
        find validation-reports -type f -print -exec cat {} \;
        
        # Convert TSV report to JSON if needed
        if [ -f validation-reports/report.tsv ]; then
          python3 -c "
import pandas as pd, json
df = pd.read_csv('validation-reports/report.tsv', sep='\t')
df.to_json('validation-reports/report.json', orient='records')
"
        fi

    - name: Upload validation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: validation-artifacts
        path: |
          automobile_merged.ttl
          validation-reports/
        retention-days: 7

    - name: Check validation status
      if: ${{ steps.robot_validation.outcome == 'failure' }}
      run: |
        if [ -f validation-reports/report.tsv ]; then
          errors=$(grep -c "ERROR" validation-reports/report.tsv || echo 0)
          echo "Found $errors validation errors"
          if [ "$errors" -gt 0 ]; then
            echo "::error::Validation failed with $errors errors"
            exit 1
          fi
        else
          echo "::error::No validation report generated"
          exit 1
        fi