name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache \
          bash \
          python3 \
          py3-pip \
          openjdk17-jre \
          wget
        
        # Install ROBOT 1.9.4 (last version with validate command)
        wget https://github.com/ontodev/robot/releases/download/v1.9.4/robot.jar \
          -O /usr/local/bin/robot.jar
        echo '#!/bin/sh' > /usr/local/bin/robot
        echo 'java -jar /usr/local/bin/robot.jar "$@"' >> /usr/local/bin/robot
        chmod +x /usr/local/bin/robot

    - name: Verify files
      run: |
        [ -f 01_core/01_classes.ttl ] || { echo "Missing 01_classes.ttl"; exit 1; }
        [ -f 01_core/02_object_properties.ttl ] || { echo "Missing 02_object_properties.ttl"; exit 1; }
        [ -f 02_instances/02_engines.ttl ] || { echo "Missing 02_engines.ttl"; exit 1; }

    - name: Merge ontology
      run: |
        chmod +x scripts/merge_ontology.sh
        ./scripts/merge_ontology.sh . automobile_merged.ttl

    - name: Validate with RIOT
      run: riot --validate automobile_merged.ttl

    - name: Validate with ROBOT
      run: |
        # For newer ROBOT versions use:
        robot report --input automobile_merged.ttl --output-dir ./validation-reports
        
        # OR for ROBOT 1.9.4:
        robot validate --input automobile_merged.ttl --output-dir ./validation-reports

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ontology-artifacts
        path: |
          automobile_merged.ttl
          validation-reports/*
        retention-days: 5