name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full repository history

    - name: Verify ontology files
      run: |
        echo "Checking required files..."
        [ -d auto-ontology/01_core ] || { echo "Missing core directory"; exit 1; }
        [ -f auto-ontology/01_core/01_classes.ttl ] || { echo "Missing classes file"; exit 1; }
        [ -f auto-ontology/01_core/02_object_properties.ttl ] || { echo "Missing properties file"; exit 1; }
        echo "All required files present"

    - name: Install Alpine dependencies
      run: |
        apk update
        apk add --no-cache \
          python3 \
          py3-pip \
          openjdk17-jre \
          bash \
          coreutils \
          findutils

    - name: Set up Python virtual environment
      run: |
        python3 -m venv /opt/venv
        source /opt/venv/bin/activate
        pip install --no-cache-dir robotframework rdflib
        echo "/opt/venv/bin" >> $GITHUB_PATH

    - name: Make scripts executable
      run: |
        chmod +x scripts/merge_ontology.sh
        chmod +x scripts/validate_sparql.sh

    - name: Merge ontology (with debug)
      run: |
        source /opt/venv/bin/activate
        echo "Current directory: $(pwd)"
        echo "Files in auto-ontology/01_core:"
        ls -la auto-ontology/01_core/
        ./scripts/merge_ontology.sh auto-ontology automobile_merged.ttl

    - name: Basic RDF validation
      run: riot --validate automobile_merged.ttl

    - name: Upload validation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ontology-artifacts
        path: automobile_merged.ttl
        retention-days: 5