name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache \
          bash \
          python3 \
          py3-pip \
          openjdk17-jre \
          wget \
          curl

        # Install latest ROBOT (correct URL)
        ROBOT_URL=$(curl -s https://api.github.com/repos/ontodev/robot/releases/latest | grep "browser_download_url.*jar" | cut -d '"' -f 4)
        wget "$ROBOT_URL" -O /usr/local/bin/robot.jar
        
        # Create robot wrapper script
        echo '#!/bin/sh' > /usr/local/bin/robot
        echo 'java -jar /usr/local/bin/robot.jar "$@"' >> /usr/local/bin/robot
        chmod +x /usr/local/bin/robot

    - name: Verify installation
      run: |
        robot --version
        riot --version

    - name: Merge ontology
      run: |
        chmod +x scripts/merge_ontology.sh
        ./scripts/merge_ontology.sh . automobile_merged.ttl

    - name: Validate with RIOT
      run: riot --validate automobile_merged.ttl

    - name: Validate with ROBOT
      run: |
        mkdir -p validation-reports
        robot report --input automobile_merged.ttl --output validation-reports/report.json
        robot verify --input automobile_merged.ttl --queries sparql/validation_queries/*.rq --output-dir validation-reports/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ontology-artifacts
        path: |
          automobile_merged.ttl
          validation-reports/*
        retention-days: 5