name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug repository structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -R
        echo "Checking required files..."
        [ -f 01_core/01_classes.ttl ] || { echo "Missing 01_classes.ttl"; exit 1; }
        [ -f 01_core/02_object_properties.ttl ] || { echo "Missing 02_object_properties.ttl"; exit 1; }
        [ -f 02_instances/02_engines.ttl ] || { echo "Missing 02_engines.ttl"; exit 1; }

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache bash python3 py3-pip openjdk17-jre
        python3 -m venv /opt/venv
        source /opt/venv/bin/activate
        pip install robotframework rdflib

    - name: Merge ontology
      run: |
        chmod +x scripts/merge_ontology.sh
        ./scripts/merge_ontology.sh . automobile_merged.ttl
        ls -lh

    - name: Validate ontology
      run: |
        riot --validate automobile_merged.ttl
        robot validate --input automobile_merged.ttl --output-dir ./validation-reports

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ontology-artifacts
        path: |
          automobile_merged.ttl
          validation-reports/*