name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Alpine dependencies
      run: |
        apk update
        apk add --no-cache \
          python3 \
          py3-pip \
          openjdk17-jre \
          bash \
          coreutils

    - name: Set up Python virtual environment
      run: |
        python3 -m venv /opt/venv
        source /opt/venv/bin/activate
        pip install --no-cache-dir robotframework rdflib
        echo "/opt/venv/bin" >> $GITHUB_PATH

    - name: Make scripts executable
      run: |
        chmod +x scripts/merge_ontology.sh
        chmod +x scripts/validate_sparql.sh

    - name: Merge ontology
      run: |
        source /opt/venv/bin/activate
        ./scripts/merge_ontology.sh auto-ontology automobile_merged.ttl

    - name: Basic RDF validation
      run: riot --validate automobile_merged.ttl

    - name: OWL validation with ROBOT
      run: |
        source /opt/venv/bin/activate
        robot validate --input automobile_merged.ttl \
          --output-dir ./validation-reports \
          --profile owl-el

    - name: Upload validation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ontology-artifacts
        path: |
          automobile_merged.ttl
          validation-reports/*
        retention-days: 5