name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ontology-validation:
    runs-on: ubuntu-latest
    container: 
      image: stain/jena
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache bash python3 py3-pip openjdk17-jre wget
        wget https://github.com/ontodev/robot/releases/latest/download/robot.jar -O /usr/local/bin/robot.jar
        echo '#!/bin/sh\njava -jar /usr/local/bin/robot.jar "$@"' > /usr/local/bin/robot
        chmod +x /usr/local/bin/robot

    - name: Merge ontology
      run: |
        chmod +x scripts/merge_ontology.sh
        ./scripts/merge_ontology.sh . automobile_merged.ttl

    - name: Basic RDF validation
      run: riot --validate automobile_merged.ttl

    - name: Run ROBOT validation (continue on error)
      continue-on-error: true
      run: |
        mkdir -p validation-reports
        robot report --input automobile_merged.ttl --output validation-reports/report.json
        robot verify --input automobile_merged.ttl --queries sparql/validation_queries/*.rq --output-dir validation-reports/
        echo "Validation completed with $(grep -c "level.: \"ERROR\"" validation-reports/report.json) errors"

    - name: Upload validation reports
      uses: actions/upload-artifact@v4
      with:
        name: validation-reports
        path: validation-reports/
        retention-days: 7

    - name: Check for critical errors
      if: ${{ failure() && steps.robot_validation.outcome == 'failure' }}
      run: |
        echo "::warning::Ontology validation failed with errors"
        echo "Number of errors found: $(grep -c "level.: \"ERROR\"" validation-reports/report.json)"
        echo "Please check the uploaded validation reports"