name: Ontology CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Apache Jena
      run: |
        sudo apt-get update
        sudo apt-get install -y jena

    - name: Make script executable
      run: chmod +x scripts/merge_ontology.sh

    - name: Merge and validate ontology
      run: |
        ./scripts/merge_ontology.sh auto-ontology automobile_merged.ttl
        riot --validate automobile_merged.ttl
        
    - name: Upload merged ontology
      uses: actions/upload-artifact@v3
      with:
        name: merged-ontology
        path: automobile_merged.ttl

    - name: Validate with ROBOT
      uses: oborel/robot-actions@v1.7.0
      with:
        command: "validate --input automobile_merged.ttl"
        
    - name: Run SPARQL validation queries
      run: |
        apt-get install -y jena
        sparql --data automobile_merged.ttl --query sparql/validate.rq